version: '3'
services:
    app:
        ports:
            - 1234
        build: .
        tty: true
        volumes:
            - .:/go/src/go_server

    app2:
        ports:
            - 1234
        build: .
        tty: true
        volumes:
            - .:/go/src/go_server
    
    proxy:
        build: ./proxy
        links:
            - app:app
            - app2:app2
        ports:
            - 1234:1234
