version: '3'
services:
    app:
        build: .
        tty: true
        volumes:
            - .:/go/src/go_server
        restart: unless-stopped

    proxy:
        build: ./proxy
        links:
            - app:app
        ports:
            - 1234:1234 
        restart: unless-stopped

    flask:
        ports:
            - 8080:8080
        build: ./support_version
        tty: true
        volumes:
            - ./support_version:/home/docker/src
        restart: unless-stopped
