version: '3'
services:
    app_test:
        build: .
        tty: true
        volumes:
            - .:/go/src/go_server
        restart: unless-stopped
    
    proxy_test:
        build: ./proxy
        links:
            - app_test:app_test
        ports:
            - 1235:1234 
        restart: unless-stopped

    flask_test:
        ports:
            - 8081:8080
        build: ./support_version
        tty: true
        volumes:
            - ./support_version:/home/docker/src
        restart: unless-stopped
