name: testDeploy

on:
  push:
    branches: [test]

jobs:
  deploy:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          # execute "SSH" and "git pull"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
          cd /home/$USER_NAME/go_server &&
          git checkout test &&
          git fetch --all &&
          git reset --hard origin/test &&
          git pull origin test 
          "
