name: testDeploy

on:
  push:
    tags:
      - 'v\d\.\d\.\d-test'

jobs:
  deploy:
    if: github.event.base_ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch 
        uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          TAG: ${{ github.ref }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
          cd /home/$USER_NAME/test/go_server && \
          git fetch origin +$TAG:$TAG --no-tags && \
          git reset --hard $TAG && \
          git co $TAG && \
          make test
          "
